<a href="https://colab.research.google.com/github/deedee-ke/practice/blob/main/CHAPTER_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
symbols = '$¢£¥€¤'
codes = []
for symbol in symbols:
  codes.append(ord(symbol))

codes

[36, 162, 163, 165, 8364, 164]

In [2]:
symbols = '$¢£¥€¤'

codes = [ord(symbol) for symbol in symbols]
codes

[36, 162, 163, 165, 8364, 164]

In [3]:
x = 'ABC'
dummy = [ord(x) for x in x]
x

'ABC'

In [4]:
dummy

[65, 66, 67]

In [5]:
symbols = '$¢£¥€¤'
beyond_ascii = [ord(s) for s in symbols if ord(s) > 127]
beyond_ascii

[162, 163, 165, 8364, 164]

In [6]:
beyond_ascii = list(filter(lambda c: c > 127, map(ord, symbols)))
beyond_ascii

[162, 163, 165, 8364, 164]

In [7]:
colors = ['black', 'white']
sizes = ['S', 'M', 'L']
tshirts = [(color, size) for color in colors for size in sizes]
tshirts

[('black', 'S'),
 ('black', 'M'),
 ('black', 'L'),
 ('white', 'S'),
 ('white', 'M'),
 ('white', 'L')]

In [8]:
for color in colors:
  for size in sizes:
    print((color, size))

('black', 'S')
('black', 'M')
('black', 'L')
('white', 'S')
('white', 'M')
('white', 'L')


In [9]:
tshirts = [(color, size) for size in sizes
                         for color in colors]

In [10]:
tshirts

[('black', 'S'),
 ('white', 'S'),
 ('black', 'M'),
 ('white', 'M'),
 ('black', 'L'),
 ('white', 'L')]

In [11]:
#self._cards = [Card(rank, suit) for suit in self.suits
                                #for rank in self.ranks]

IndentationError: ignored

In [14]:
symbols = '$¢£¥€¤'
tuple(ord(symbol) for symbol in symbols)

(36, 162, 163, 165, 8364, 164)

In [15]:
import array
array.array('I', (ord(symbol) for symbol in symbols))

array('I', [36, 162, 163, 165, 8364, 164])

In [16]:
colors

['black', 'white']

In [17]:
sizes

['S', 'M', 'L']

In [18]:
for tshirt in ('%s %s' % (c, s) for c in colors for s in sizes):
  print(tshirt)

black S
black M
black L
white S
white M
white L


In [19]:
lax_coordinates = (33.9425, -118.408056)
city, year, pop, chg, area = ('Tokyo', 2003, 32450, 0.66, 8014)
traveler_ids = [('USA', '31195855'), ('BRA', 'CE342567'), ('ESP', 'XDA205856')]
for passport in sorted(traveler_ids):
  print('%s/%s' % passport)

BRA/CE342567
ESP/XDA205856
USA/31195855


In [20]:
for country, _ in traveler_ids:
  print(country)

USA
BRA
ESP


In [21]:
lax_coordinates

(33.9425, -118.408056)

In [22]:
latitude, longitude = lax_coordinates
latitude

33.9425

In [23]:
longitude

-118.408056

In [24]:
#b, a = a, b

In [25]:
divmod(20, 8)

(2, 4)

In [26]:
t = (20, 8)
divmod(*t)

(2, 4)

In [27]:
quotient, remainder = divmod(*t)
quotient, remainder

(2, 4)

In [28]:
import os
_, filename = os.path.split('/home/luciano/.ssh/idrsa.pub')
filename

'idrsa.pub'

In [29]:
a, b, *rest = range(5)
a, b, rest

(0, 1, [2, 3, 4])

In [30]:
a, b, *rest = range(3)
a, b, rest

(0, 1, [2])

In [31]:
a, b, *rest = range(2)
a, b, rest

(0, 1, [])

In [32]:
a, *body, c, d = range(5)
a, body, c, d

(0, [1, 2], 3, 4)

In [33]:
*head, b, c, d = range(5)
head, b, c, d

([0, 1], 2, 3, 4)

In [34]:
metro_areas = [
 ('Tokyo', 'JP', 36.933, (35.689722, 139.691667)),
 ('Delhi NCR', 'IN', 21.935, (28.613889, 77.208889)),
 ('Mexico City', 'MX', 20.142, (19.433333, -99.133333)),
 ('New York-Newark', 'US', 20.104, (40.808611, -74.020386)),
 ('Sao Paulo', 'BR', 19.649, (-23.547778, -46.635833)),
]

print('{:15} | {:^9} | {:^9}'.format('', 'lat.', 'long.'))
fmt = '{:15} | {:9.4f} | {:9.4f}'
for name, cc, pop, (latitude, longitude) in metro_areas:
  if longitude <= 0:
    print(fmt.format(name, latitude, longitude))


                |   lat.    |   long.  
Mexico City     |   19.4333 |  -99.1333
New York-Newark |   40.8086 |  -74.0204
Sao Paulo       |  -23.5478 |  -46.6358


In [35]:
import collections
Card = collections.namedtuple('Card', ['rank', 'suit'])

In [36]:
from collections import namedtuple
City = namedtuple('City', 'name country population coordinates')
tokyo = City('Tokyo', 'JP', 36.933, (35.689722, 139.691667))
tokyo

City(name='Tokyo', country='JP', population=36.933, coordinates=(35.689722, 139.691667))

In [37]:
tokyo.population

36.933

In [38]:
tokyo.coordinates

(35.689722, 139.691667)

In [39]:
City._fields

('name', 'country', 'population', 'coordinates')

In [40]:
LatLong = namedtuple('LatLong', 'lat long')
delhi_data = ('Delhi NCR', 'IN', 21.935, LatLong(28.613889, 77.208889))
delhi = City._make(delhi_data)
delhi._asdict()


{'name': 'Delhi NCR',
 'country': 'IN',
 'population': 21.935,
 'coordinates': LatLong(lat=28.613889, long=77.208889)}

In [41]:
for key, value in delhi._asdict().items():
  print(key + ':', value)

name: Delhi NCR
country: IN
population: 21.935
coordinates: LatLong(lat=28.613889, long=77.208889)


In [42]:
l = [10, 20, 30, 40, 50, 60]
l[:2]

[10, 20]

In [43]:
l[2:]

[30, 40, 50, 60]

In [44]:
l[:3]

[10, 20, 30]

In [45]:
l[3:]

[40, 50, 60]

In [46]:
s = 'bicycle'
s[::3]

'bye'

In [47]:
s[::-1]

'elcycib'

In [48]:
s[:: -2]

'eccb'

In [49]:
invoice = """
0.....6.................................40........52...55........
1909  Pimoroni PiBrella                     $17.50    3    $52.50
1489  6mm Tactile Switch x20                $4.95     2    $9.90
1510  Panavise Jr. - PV-201                 $28.00    1    $28.00
1601  PiTFT Mini Kit 320x240                $34.95    1    $34.95"""
SKU = slice(0,6)
DESCRIPTION = slice(6, 40)
UNIT_PRICE = slice(40, 52)
QUANTITY = slice(52, 55)
ITEM_TOTAL = slice(55, None)

line_items = invoice.split("\n")[2:]
for item in line_items:
    print(item[DESCRIPTION] + ": PRICE IS : "+item[UNIT_PRICE])

Pimoroni PiBrella                 : PRICE IS :     $17.50  
6mm Tactile Switch x20            : PRICE IS :     $4.95   
Panavise Jr. - PV-201             : PRICE IS :     $28.00  
PiTFT Mini Kit 320x240            : PRICE IS :     $34.95  


In [51]:
l = list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [52]:
l[2:5] = [20, 30]
l

[0, 1, 20, 30, 5, 6, 7, 8, 9]

In [53]:
del l[5:7]
l

[0, 1, 20, 30, 5, 8, 9]

In [54]:
l[3::2] = [11, 22]
l

[0, 1, 20, 11, 5, 22, 9]

In [56]:
l[2:5] = [100]
l

[0, 1, 100]

In [57]:
l = [1, 2, 3]
l * 5

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [58]:
5 * 'abcd'

'abcdabcdabcdabcdabcd'

In [59]:
board = [['_'] * 3 for i in range(3)]
board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [60]:
board[1][2] = 'X'
board

[['_', '_', '_'], ['_', '_', 'X'], ['_', '_', '_']]

In [61]:
weird_board = [['_'] * 3] * 3
weird_board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [62]:
weird_board[1][2] = '0'
weird_board

[['_', '_', '0'], ['_', '_', '0'], ['_', '_', '0']]

In [63]:
row = ['_'] * 3
board = []
for i in range(3):
  board.append(row)

In [64]:
board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [65]:
board = []
for i in range(3):
  row = ['_'] * 3
  board.append(row)

board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [66]:
board[2][0] = 'X'
board

[['_', '_', '_'], ['_', '_', '_'], ['X', '_', '_']]

In [67]:
l = [1, 2, 3]
id(l)

138670816917312

In [68]:
l *= 2
l

[1, 2, 3, 1, 2, 3]

In [69]:
id(l)

138670816917312

In [70]:
t = (1, 2, 3)
id(t)

138670816871296

In [71]:
t *= 2
id(t)

138670818672800

In [72]:
t = (1, 2, [30, 40])
#t[2] += [50, 60]

TypeError: ignored

In [73]:
t

(1, 2, [30, 40, 50, 60])

In [74]:
fruits = ['grape', 'raspberry', 'apple', 'banana']
sorted(fruits)

['apple', 'banana', 'grape', 'raspberry']

In [75]:
fruits

['grape', 'raspberry', 'apple', 'banana']

In [76]:
sorted(fruits, reverse=True)

['raspberry', 'grape', 'banana', 'apple']

In [77]:
fruits

['grape', 'raspberry', 'apple', 'banana']

In [78]:
fruits.sort()
fruits

['apple', 'banana', 'grape', 'raspberry']

In [80]:
import bisect
import sys

HAYSTACK = [1, 4, 5, 6, 8, 12, 15, 20, 21, 23, 23, 26, 29, 30]
NEEDLES = [0, 1, 2, 5, 8, 10, 22, 23, 29, 30, 31]

ROW_FMT = '{0:2d} @ {1:2d}    {2}{0:<2d}'

def demo(bisect_fn):
    for needle in reversed(NEEDLES):
        position = bisect_fn(HAYSTACK, needle)  # (1)
        offset = position * '  |'  # (2)
        print(ROW_FMT.format(needle, position, offset))  # (3)

if __name__ == '__main__':

    if sys.argv[-1] == 'left':    # (4)
        bisect_fn = bisect.bisect_left
    else:
        bisect_fn = bisect.bisect

    print('DEMO:', bisect_fn.__name__)  # (5)
    print('haystack ->', ' '.join(f'{n:2}' for n in HAYSTACK))
    demo(bisect_fn)

DEMO: bisect_right
haystack ->  1  4  5  6  8 12 15 20 21 23 23 26 29 30
31 @ 14      |  |  |  |  |  |  |  |  |  |  |  |  |  |31
30 @ 14      |  |  |  |  |  |  |  |  |  |  |  |  |  |30
29 @ 13      |  |  |  |  |  |  |  |  |  |  |  |  |29
23 @ 11      |  |  |  |  |  |  |  |  |  |  |23
22 @  9      |  |  |  |  |  |  |  |  |22
10 @  5      |  |  |  |  |10
 8 @  5      |  |  |  |  |8 
 5 @  3      |  |  |5 
 2 @  1      |2 
 1 @  1      |1 
 0 @  0    0 


In [84]:
def grade(score, breakpoints=[60, 70, 80, 90], grades='FDCBA'):
    i = bisect.bisect(breakpoints, score)
    return grades[i]

[grade(score) for score in [33, 99, 77, 70, 89, 90, 100]]

['F', 'A', 'C', 'C', 'B', 'A', 'A']

In [85]:
import bisect
import random

SIZE = 7

random.seed(1729)

my_list = []
for i in range(SIZE):
    new_item = random.randrange(SIZE*2)
    bisect.insort(my_list, new_item)
    print('%2d ->' % new_item, my_list)

10 -> [10]
 0 -> [0, 10]
 6 -> [0, 6, 10]
 8 -> [0, 6, 8, 10]
 7 -> [0, 6, 7, 8, 10]
 2 -> [0, 2, 6, 7, 8, 10]
10 -> [0, 2, 6, 7, 8, 10, 10]


In [86]:
from array import array
from random import random

floats = array('d', (random() for i in range(10**7)))
floats[-1]

0.5963321947530882

In [87]:
fp = open('floats.bin', 'wb')
floats.tofile(fp)
fp.close()
floats2 = array('d')
fp = open('floats.bin', 'rb')
floats2.fromfile(fp, 10**7)
fp.close()
floats2[-1]

0.5963321947530882

In [89]:
floats2 == floats

True

In [95]:
import array
numbers = array.array('h', [-2, -1, 0, 1, 2])
memv = memoryview(numbers)
len(memv)

5

In [96]:
memv[0]

-2

In [97]:
memv_oct = memv.cast('B')
memv_oct.tolist()

[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]

In [98]:
memv_oct[5] = 4
numbers

array('h', [-2, -1, 1024, 1, 2])

In [99]:
import numpy
a = numpy.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [100]:
type(a)

numpy.ndarray

In [101]:
a.shape

(12,)

In [102]:
a.shape = 3, 4
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [103]:
a[2]

array([ 8,  9, 10, 11])

In [104]:
a[2, 1]

9

In [106]:
a[:,1]

array([1, 5, 9])

In [107]:
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [108]:
import numpy
floats = numpy.loadtxt('floats-10M-lines.txt')
floats[-3:]
floats *= .5


FileNotFoundError: ignored

In [109]:
from collections import deque
dq = deque(range(10), maxlen=10)
dq

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [110]:
dq.rotate(3)
dq

deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6])

In [111]:
dq.rotate(-4)
dq

deque([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [112]:
dq.appendleft(-1)
dq

deque([-1, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [113]:
dq.extend([11, 22, 33])
dq

deque([3, 4, 5, 6, 7, 8, 9, 11, 22, 33])

In [114]:
dq.extendleft([10, 20, 30, 40])
dq

deque([40, 30, 20, 10, 3, 4, 5, 6, 7, 8])